GET http://localhost:3000/login

###

POST http://localhost:3000/login/register
Content-Type: application/json

{
			"username": "thomas",
			"password": "123"
}

###

POST http://localhost:3000/login/try
Content-Type: application/json

{
            "username": "thomas",
            "password": "123"
}